// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUYybVTzdWaHglc82kSNqgK3UnKGIkNj4',
    appId: '1:137313096799:web:4a854356a646e8de05f7ea',
    messagingSenderId: '137313096799',
    projectId: 'planner-app-371ca',
    authDomain: 'planner-app-371ca.firebaseapp.com',
    storageBucket: 'planner-app-371ca.firebasestorage.app',
    measurementId: 'G-X2VD5SC5BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbC27qHsHY1yHzY2Nnr7sKlYnh2f6XTdI',
    appId: '1:137313096799:android:756896d0b6b621f705f7ea',
    messagingSenderId: '137313096799',
    projectId: 'planner-app-371ca',
    storageBucket: 'planner-app-371ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_Cjh3Qw3XZGfmbGs3AU138a15FVJ_f8',
    appId: '1:137313096799:ios:c9ddd4b4a41bb9b305f7ea',
    messagingSenderId: '137313096799',
    projectId: 'planner-app-371ca',
    storageBucket: 'planner-app-371ca.firebasestorage.app',
    iosBundleId: 'com.example.plannerApp',
  );
}